name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: firebase login:ci --interactive

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        