name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Mude para o nome da sua branch principal, se for diferente
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      - name: Authenticate Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase auth:ci
      
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --project lucas-website-29f26