name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

     - name: Authenticate Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase auth:ci

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        